---
message: "This node is using Production Tier Data"



awt:network:domain_name: 'samdom.aussieswithtails.fuzz'


awt::puppet::server:
    id: 'oberon'
    fqdn: 'oberon.samdom.aussieswithtails.fuzzbutt'


puppetdb::master::config::db_server: 'puppet01.samdom.aussieswithtails.fuzzbutt'


