---
message: "This node is using Production Tier Data"
# Data for PuppetDB
puppetdb::listen_port: '18080'
puppetdb::ssl_listen_port: '18081'
puppetdb::database_name: 'puppetdb'
puppetdb::database_password: 'teABoNlARTErYGmATo'
puppetdb::database_username: 'puppetdb'
puppetdb::service_status: 'running'
puppetdb::master::config::puppetdb_port: "18081"

awt::user::snesbitt:
  ssh_key_content: 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA0fSQTmZM1YiWAYIVfS5vgrGwst9SGQMcDMheKlrar2wW7Y262JDQWgf8FCZjn4t4FG2L6z4VFNKLRg2UIwmh2uT3p9+sul0oyWrVeukYUrslZl5wrZxpuy1OgVJSeoATmB0JTzIIPu+eQDsCDNthUH+cGTBDKkhquRvmBo/jZ4CPEpqANh6wWpQJQUPIzoCiS+mBtl+0dI2BReFr/SVH9ebZ3vmc+vBZppqz7EqHdeL8psgqGkFA+YNYN0qDKSdU4mWgOkvsTDCWGkeAq4Yn8Kir0mntYE4lFcSFOflLJLgX9k3m9RVy2O4tsCujtX6fKWC/zi+J96Dtso56Xgoi/Q== snesbitt@loki'

awt::puppet::server:
    id: 'oberon'
    fqdn: 'oberon.samdom.aussieswithtails.fuzzbutt'

