# Class: profile::z_way_server
#
# This class installs, configures a z_way_server. See http://razberry.z-wave.me/index.php?id=24
#
# Sample Usage:
#
#   include ::profile::z_way_server

class profile::z_way_server {
  if $facts['architecture'] !~ /^arm.*/ {
    fail("${name} requires architecture of type: arm")
  }

  $expect_script = '/tmp/install_z_way_server.exp'
  $install_script = '/tmp/install_z_way_server.sh'

  $expect_content = @("END_OF_SCRIPT"/$)
      #!/usr/bin/expect -f
      #
      # This Expect script was generated by autoexpect on Wed Mar 23 23:04:16 2016
      # Expect and autoexpect were both written by Don Libes, NIST.
      #
      # Purpose of this script is to automate running of the z_way_server
      # installation script which includes 2 user queries - acceptance of
      # the license agreement, and yes/no to emails.


      set force_conservative 0
      if {\$force_conservative} {
        set send_slow {1 .1}
        proc send {ignore arg} {
          sleep .1
          exp_send -s -- \$arg
        }
      }

      set timeout -1
      spawn \$env(SHELL)
      match_max 100000
      send -- "sudo /bin/bash ${install_script}\r"
      expect "Do you accept Z-Wave.Me licence agreement?\r
      Please read it on Z-Wave.Me web site: http://razberry.z-wave.me/docs/ZWAYEULA.pdf\r
      yes/no: "
      send -- "yes\r"
      expect "Do you want to receive emails with news about RaZberry project?\r
      ! Please subscribe again if you did it before 30.03.2013\r
      yes/no: "
      send -- "no\r"
      | @END_OF_SCRIPT

  package { 'expect':
    ensure  => present,
  }

  wget::fetch {'z_way_server install script':
    source      => 'http://razberry.z-wave.me/install',
    destination => '/tmp/install_z_way_server.sh',
    verbose     => true,
  }

  file { $expect_script:
    ensure  => file,
    mode    => '0755',
    content => $expect_content,
  }

  exec {$expect_script:
    onlyif  => $expect_script,
    require => File[$expect_script]
  }

}